### ISSUE TITLE
Button.png

### ISSUE THREAD

**Issue by DannyJoris** [bmx269/parrot#17]
Compiling with compass throws an error for this line: https://github.com/bmx269/parrot/blob/7.x-1.x/css/sass/base/_forms.scss#L88

This line should be `background: #dddddd image-url("button.png") repeat-x;`.

Image-url will use the path set for images from config.rb, so it should not be written as relative to the .css file. That's only if you just use url().

**Comment by bmx269** [comment]
Fixed. Thanks Danny
